import streamlit as st
import pandas as pd
from myproject.data_loader import sync_table_changes

def render_data_manager(jobs_df: pd.DataFrame, apps_df: pd.DataFrame, events_df: pd.DataFrame):
    st.subheader("🗄️ Database Manager")
    st.caption("Inline edit, add, or delete rows. Changes will be synced to Supabase when you save.")
    
    table_choice = st.selectbox("Select Table to Manage", ["Jobs", "Job Applications", "Job Events"])
    
    df_to_edit = pd.DataFrame()
    table_name = ""
    
    if table_choice == "Jobs":
        df_to_edit = jobs_df.copy()
        table_name = 'jobs'
    elif table_choice == "Job Applications":
        df_to_edit = apps_df.copy()
        table_name = 'job_applications'
    elif table_choice == "Job Events":
        df_to_edit = events_df.copy()
        table_name = 'job_application_events'
        
    if df_to_edit.empty:
        st.info("No data available in this table.")
        return
        
    editor_key = f"editor_{table_name}"
    
    # Configure the column configurations, particularly disabling the 'id' column
    column_config = {}
    if 'id' in df_to_edit.columns:
        column_config['id'] = st.column_config.NumberColumn(
            "ID",
            disabled=True,
            help="Primary Key (Auto-generated by Supabase)"
        )
    if 'application_id' in df_to_edit.columns:
        column_config['application_id'] = st.column_config.NumberColumn("Application ID")
    if 'job_id' in df_to_edit.columns:
        column_config['job_id'] = st.column_config.NumberColumn("Job ID")
    
    with st.form(key=f"form_{table_name}"):
        edited_df = st.data_editor(
            df_to_edit,
            num_rows="dynamic",
            use_container_width=True,
            key=editor_key,
            column_config=column_config
        )
        
        submit = st.form_submit_button("💾 Sync Changes to Supabase", type="primary")
        
        if submit:
            changes = st.session_state.get(editor_key, {})
            has_changes = any(len(v) > 0 for v in changes.values() if isinstance(v, (list, dict)))
            
            if not has_changes:
                st.info("No changes to sync.")
            else:
                success, msg = sync_table_changes(table_name, df_to_edit, changes)
                if success:
                    st.toast(f"✅ {msg}")
                    st.rerun()
                else:
                    st.error(f"❌ {msg}")

    st.divider()
    with st.expander("⚠️ Danger Zone / Advanced Actions"):
        st.warning("These actions perform bulk database operations. Use with caution.")
        st.markdown("**Migrate Data**: Move all records from `job_applications` (Historical) into the `jobs` (Live) table.")
        
        if st.button("🚀 Migrate Historical Data to Live Jobs", type="primary"):
            from myproject.data_loader import migrate_historical_to_live
            with st.spinner("Migrating data..."):
                success, msg, count = migrate_historical_to_live()
                if success:
                    st.success(f"✅ {msg}")
                    if count > 0:
                        import time
                        time.sleep(1.5)
                        st.rerun()
                else:
                    st.error(f"❌ {msg}")
